spring:

  liquibase:
    enabled: true
    drop-first: false
    change-log: db/changelog/database-monitoring-service-changelog.xml
    default-schema: monitoring_service
    liquibase-schema: settings
    schemas: audit

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false&currentSchema=monitoring_service
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  auditsource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false&currentSchema=audit
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  liquibasesource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

permission:
  unauthorized:
    urls: /api/v1/auth/**,/v3/api-docs/**,/v2/api-docs,/configuration/ui,/swagger-resources/**,/configuration/security,/swagger-ui.html,/webjars/**

validator:
  credential:
    emailPattern: ^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$
    passwordPattern: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()â€“[{}]:;',?/*~$^+=<>]).{8,20}$